import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppinsBlack = localFont({
  src: "./fonts/Poppins-Black.ttf",
  variable: "--font-poppins-regular",
  weight: "100 900",
});
const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsRegular.variable} ${poppinsBlack.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
